# Generated by Django 5.2 on 2025-05-21 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackedstock',
            name='image',
            field=models.ImageField(blank=True, upload_to='stock_images/'),
        ),
    ]
