# Generated by Django 5.2 on 2025-05-21 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockiz', '0002_trackedstock_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackedstock',
            name='symbol',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
